development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: meganreel
  password: m0e1r4n
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: meganreel
  password: m0e1r4n